# name: Build and Test

# on:
#   push:
#     branches:
name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build client
      run: npm ci --prefix daniel-portfolio.client && npm run build --prefix daniel-portfolio.client
